[pytest]
pythonpath =
    .
    services/authentication-service
    services/tenant-service
    services/notification-service
    shared
testpaths = services/authentication-service/app/tests
addopts = -q
filterwarnings =
    ignore::DeprecationWarning
