"""auth_domain_improvements

Revision ID: 3832b17a0112
Revises: 2d271a05e50c
Create Date: 2026-09-01 12:48:38.005092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3832b17a0112'
down_revision: Union[str, Sequence[str], None] = '2d271a05e50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # auth_otp: add updated_at audit column
    with op.batch_alter_table('auth_otp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # auth_refresh_tokens: add revoked_at timestamp for audit + reuse detection
    with op.batch_alter_table('auth_refresh_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revoked_at', sa.DateTime(), nullable=True))

    # tenants: add unique tenant_code identifier
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_code', sa.String(length=32), nullable=True))
        batch_op.create_index(op.f('ix_tenants_tenant_code'), ['tenant_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_tenants_tenant_code'))
        batch_op.drop_column('tenant_code')

    with op.batch_alter_table('auth_refresh_tokens', schema=None) as batch_op:
        batch_op.drop_column('revoked_at')

    with op.batch_alter_table('auth_otp', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
    # ### end Alembic commands ###
